services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
  backend:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: nest_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cinema?schema=public
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - backend_network
    command: >
      sh -c "
              npx prisma generate &&
              npx prisma migrate deploy &&
              npm run start:dev"

volumes:
  postgres_data:

networks:
  backend_network: